// POSTS EVENTS
export const GET_ALBUMS_REQUEST = "GET_ALBUMS_REQUEST";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILED = "GET_ALBUMS_FAILED";
export const SET_ALBUMS_VIEW_SUCCESS = "SET_ALBUMS_VIEW_SUCCESS";
export const SET_DETAIL_ALBUM_SUCCESS = "SET_DETAIL_ALBUM_SUCCESS";
export const SET_DETAILVIEW_ALBUM_SUCCESS = "SET_DETAILVIEW_ALBUM_SUCCESS";
export const GET_ALBUMS_SONGS_REQUEST = "GET_ALBUMS_SONGS_REQUEST";
export const GET_ALBUMS_SONGS_SUCCESS = "GET_ALBUMS_SONGS_SUCCESS";
export const GET_ALBUMS_SONGS_FAILED = "GET_ALBUMS_SONGS_FAILED";

