// POSTS EVENTS
export const GET_ARTISTS_REQUEST = "GET_ARTISTS_REQUEST";
export const GET_ARTISTS_SUCCESS_2 = "GET_ARTISTS_SUCCESS_2";
export const GET_ARTISTS_FAILED = "GET_ARTISTS_FAILED";
export const SET_ARTISTS_VIEW_SUCCESS = "SET_ARTISTS_VIEW_SUCCESS";
export const SET_DETAIL_ARTIST_SUCCESS = "SET_DETAIL_ARTIST_SUCCESS";
export const SET_DETAILVIEW_ARTIST_SUCCESS = "SET_DETAILVIEW_ARTIST_SUCCESS";
export const GET_ARTISTS_ALBUMS_REQUEST = "GET_ARTISTS_ALBUMS_REQUEST";
export const GET_ARTISTS_ALBUMS_SUCCESS = "GET_ARTISTS_ALBUMS_SUCCESS";
export const GET_ARTISTS_ALBUMS_FAILED = "GET_ARTISTS_ALBUMS_FAILED";
