// POSTS EVENTS
export const GET_BEER_REQUEST = "GET_BEER_REQUEST";
export const GET_BEER_REFRESH = "GET_BEER_REFRESH";
export const GET_BEER_LOADMORE = "GET_BEER_LOADMORE";
export const GET_BEER_SUCCESS = "GET_BEER_SUCCESS";
export const GET_BEER_FAILED = "GET_BEER_FAILED";