// PLAYERS EVENTS

export const LOAD_AUDIO_BUFFER_REQUEST = "LOAD_AUDIO_BUFFER_REQUEST";
export const LOAD_AUDIO_BUFFER_SUCCESS = "LOAD_AUDIO_BUFFER_SUCCESS";
export const LOAD_AUDIO_BUFFER_FAILED = "LOAD_AUDIO_BUFFER_FAILED";

export const LOAD_AUDIO_CONTEXT_REQUEST = "LOAD_AUDIO_CONTEXT_REQUEST";
export const LOAD_AUDIO_CONTEXT_SUCCESS = "LOAD_AUDIO_CONTEXT_SUCCESS";
export const LOAD_AUDIO_CONTEXT_FAILED = "LOAD_AUDIO_CONTEXT_FAILED";
export const FLUSH_AUDIO_BUFFER_SUCCESS = "FLUSH_AUDIO_BUFFER_SUCCESS";

export const SHOW_AUDIO_WAVEFORM_SUCCESS = "SHOW_AUDIO_WAVEFORM_SUCCESS";
