// POSTS EVENTS
export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAILED = "GET_USER_POSTS_FAILED";
export const SET_POSTS_VIEW_SUCCESS = "SET_POSTS_VIEW_SUCCESS";
export const SET_LISTVIEW_POST_SUCCESS = "SET_LISTVIEW_POST_SUCCESS"
export const SET_DETAILVIEW_POST_SUCCESS = "SET_DETAILVIEW_POST_SUCCESS"
export const SET_DETAIL_POST_SUCCESS = "SET_DETAIL_POST_SUCCESS"