// POSTS EVENTS
export const GET_USER_SONGS_REQUEST = "GET_USER_SONGS_REQUEST";
export const GET_USER_SONGS_SUCCESS = "GET_USER_SONGS_SUCCESS";
export const GET_USER_SONGS_FAILED = "GET_USER_SONGS_FAILED";

export const RESET_USER_SONGS_REQUEST = "RESET_USER_SONGS_REQUEST";
export const RESET_USER_SONGS_SUCCESS = "RESET_USER_SONGS_SUCCESS";
export const RESET_USER_SONGS_FAILED = "RESET_SONGS_FAILED";

export const COUNT_USER_SONGS_TOTAL_REQUEST = "COUNT_USER_SONGS_TOTAL_REQUEST";
export const COUNT_USER_SONGS_TOTAL_SUCCESS = "COUNT_USER_SONGS_TOTAL_SUCCESS";
export const COUNT_USER_SONGS_TOTAL_FAILED = "COUNT_USER_SONGS_TOTAL_FAILED";