// POSTS EVENTS
export const GET_SONGS_REQUEST = "GET_SONGS_REQUEST";
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS";
export const GET_SONGS_FAILED = "GET_SONGS_FAILED";
export const RESET_SONGS_REQUEST = "RESET_SONGS_REQUEST";
export const RESET_SONGS_SUCCESS = "RESET_SONGS_SUCCESS";
export const RESET_SONGS_FAILED = "RESET_SONGS_FAILED";
export const COUNT_SONGS_TOTAL_REQUEST = "COUNT_SONGS_TOTAL_REQUEST";
export const COUNT_SONGS_TOTAL_SUCCESS = "COUNT_SONGS_TOTAL_SUCCESS";
export const COUNT_SONGS_TOTAL_FAILED = "COUNT_SONGS_TOTAL_FAILED";
export const SET_SONGS_VIEW_SUCCESS = "SET_SONGS_VIEW_SUCCESS";
export const SET_SONGS_RANDOM_SUCCESS = "SET_SONGS_RANDOM_SUCCESS";
export const SET_DETAIL_SONG_SUCCESS = "SET_DETAIL_SONG_SUCCESS";
export const SET_DETAILVIEW_SONG_SUCCESS = "SET_DETAILVIEW_SONG_SUCCESS";